EDA

In [262]:
#importing pandas library
import numpy as np
import pandas as pd

In [263]:
 df = pd.read_csv("C:/Users/Shivam Sudha/Desktop/customer_shopping_behaviour_analysis/data/unclean_data.csv")

In [264]:
df

      Customer ID  Age  Gender Item Purchased     Category  \
0             180   64    Male          Scarf     Footwear
1             831   41    Male          Boots     Clothing
2             625   55    Male          Skirt     Clothing
3            1781   67    Male          Socks  Accessories
4            1059   29    Male         Blouse  Accessories
5            1424   51    Male        Sandals     Footwear
6            3368   44  Female          Shirt     Clothing
7             264   27    Male           Belt     Clothing
8            2210   42    Male        Handbag     Footwear
9            1514   22    Male         Hoodie     Clothing
10           2756   59  Female          Socks  Accessories
11           3675   35  Female          Boots  Accessories
12            140   49    Male          Dress    Outerwear
13           2646   23    Male            Hat  Accessories
14           2944   29  Female          Skirt     Clothing
15            564   61    Male          Skirt     Footwear
16           3372   49  Female            Hat     Clothing
17           1100   19    Male          Dress     Clothing
18           1041   68    Male           Coat     Clothing
19            860   47    Male         Blouse     Clothing
20           3310   48  Female          Scarf  Accessories
21            104   54    Male          Socks     Footwear
22             87   24    Male         Hoodie     Clothing
23           1354   39    Male          Pants     Clothing
24           1772   46    Male           Coat     Clothing
25            356   37    Male           Belt  Accessories
26           1092   44    Male     Sunglasses     Clothing
27           2649   51    Male          Jeans     Clothing
28           2177   24    Male           Coat  Accessories
29           1988   69    Male        Handbag  Accessories
30           1568   30    Male          Shoes  Accessories
31            670   43    Male         Shorts    Outerwear
32           3486   50  Female          Scarf     Clothing
33            483   41    Male         Shorts  Accessories
34           3643   47  Female         Jacket     Clothing
35            774   29    Male        Jewelry  Accessories
36           2109   54    Male         Shorts     Clothing
37           1298   44    Male     Sunglasses     Footwear
38            555   56    Male     Sunglasses     Footwear
39           1049   30    Male        Handbag     Clothing
40            759   66    Male            Hat     Footwear
41           2012   57    Male     Sunglasses     Footwear
42           1113   69    Male         Gloves     Clothing
43           1204   40    Male        Jewelry     Footwear
44           1540   32    Male         Blouse  Accessories
45           2079   49    Male         Jacket     Clothing
46           1999   20    Male     Sunglasses     Clothing
47             27   38    Male          Shoes  Accessories
48           2739   50  Female          Skirt     Footwear
49           2348   37    Male        Sweater  Accessories
50           3817   29  Female       Sneakers    Outerwear
51           2068   60    Male       Sneakers     Clothing
52           2692   43  Female          Boots     Clothing
53           2968   34  Female         Gloves     Footwear
54            176   53    Male        Sandals    Outerwear
55           2919   19  Female       Sneakers  Accessories
56            798   42    Male          Boots    Outerwear
57           3172   68  Female         Blouse  Accessories
58           1211   34    Male          Shoes  Accessories
59           1736   58    Male         Hoodie     Clothing
60           2772   58  Female         Blouse    Outerwear
61            578   19    Male         Gloves     Clothing
62           2044   47    Male        Jewelry  Accessories
63            630   26    Male          Pants     Footwear
64           3662   63  Female           Coat     Footwear
65           3139   47  Female          Shirt     Clothing
66           2316   69    Male         Hoodie     Clothing
67           2828   20  Female         Shorts     Clothing
68           2354   56    Male          Pants  Accessories
69           2557   24    Male         Blouse     Clothing
70           2899   23  Female           Belt     Footwear
71           2960   38  Female        T-shirt  Accessories
72           2708   32  Female            Hat  Accessories
73           3140   35  Female         Hoodie  Accessories
74           2496   40    Male         Blouse  Accessories
75           1981   51    Male            Hat     Footwear
76           3442   64  Female            Hat     Clothing
77           1720   45    Male          Boots     Clothing
78           1751   31    Male          Jeans  Accessories
79            893   31    Male          Boots     Clothing
80           3287   45  Female        Sweater    Outerwear
81            124   57    Male        Sweater     Clothing
82           1166   51    Male        T-shirt     Clothing
83            668   34    Male         Jacket  Accessories
84           1488   40    Male         Gloves     Clothing
85            617   29    Male       Sneakers  Accessories
86           3745   24  Female        Handbag     Clothing
87            390   27    Male           Belt     Footwear
88           2873   63  Female        T-shirt  Accessories
89           2272   29    Male          Boots     Clothing
90           1410   34    Male          Socks  Accessories
91           2134   21    Male       Backpack  Accessories
92           1545   30    Male        Jewelry  Accessories
93           1439   58    Male         Jacket    Outerwear
94           2577   20    Male          Dress     Clothing
95           1549   69    Male         Jacket     Clothing
96           2310   70    Male        Jewelry     Clothing
97            867   67    Male     Sunglasses  Accessories
98           3364   58  Female        Sandals     Clothing
99            881   39    Male          Shoes  Accessories
100          2812   69  Female           Belt    Outerwear
101          1152   41    Male           Belt     Clothing
102          3293   62  Female          Dress  Accessories
103          1209   20    Male        Sweater     Footwear
104          2534   66    Male         Blouse  Accessories
105          3825   54  Female          Socks     Clothing
106          1277   51    Male          Skirt     Footwear
107           372   27    Male          Shirt     Footwear
108          2938   28  Female           Coat  Accessories
109          3037   50  Female          Shirt     Clothing
110          2244   56    Male            Hat     Clothing
111          3116   26  Female       Backpack  Accessories
112          2431   20    Male           Coat    Outerwear
113          2450   26    Male         Hoodie    Outerwear
114          1336   56    Male            Hat     Footwear
115           574   58    Male          Shirt     Clothing
116          3478   53  Female          Pants  Accessories
117           661   50    Male        T-shirt    Outerwear
118          2072   69    Male          Boots    Outerwear
119          2379   26    Male          Skirt  Accessories
120          2951   22  Female           Coat     Clothing
121           405   35    Male           Coat     Clothing
122          3750   24  Female       Backpack     Clothing
123          3600   37  Female        Handbag  Accessories
124          2343   20    Male         Jacket     Clothing
125          2300   64    Male         Shorts    Outerwear
126          1145   41    Male     Sunglasses     Clothing
127           134   52    Male     Sunglasses     Clothing
128            95   58    Male         Blouse     Clothing
129          3336   44  Female        Sweater  Accessories
130          1206   52    Male          Shirt  Accessories
131          2792   43  Female        Sweater  Accessories
132          3590   31  Female     Sunglasses  Accessories
133           805   43    Male          Socks     Footwear
134           428   58    Male         Hoodie  Accessories
135          3491   62  Female        T-shirt     Footwear
136          2981   70  Female          Shirt  Accessories
137          2453   68    Male         Blouse     Clothing
138          1395   26    Male         Blouse    Outerwear
139          2706   65  Female        Sandals    Outerwear
140          1427   60    Male          Pants     Clothing
141          2378   44    Male          Shirt     Clothing
142          3086   24  Female         Hoodie     Clothing
143          2146   38    Male          Scarf     Clothing
144          1726   45    Male        Sweater  Accessories
145          1055   18    Male          Dress     Clothing
146          3114   46  Female       Backpack     Clothing
147           686   70    Male          Jeans     Clothing
148          1707   37    Male          Shoes  Accessories
149           815   31    Male           Coat     Clothing
150          1404   26    Male        Sandals  Accessories
151          1526   29    Male          Socks  Accessories
152          2771   50  Female        Handbag     Footwear
153          3829   42  Female         Blouse     Clothing
154          1512   34    Male         Blouse     Clothing
155          3483   66  Female       Backpack  Accessories
156          3317   42  Female       Backpack     Clothing
157          2505   56    Male         Jacket     Clothing
158           863   19    Male          Scarf    Outerwear
159           571   65    Male        Jewelry     Clothing
160           672   38    Male            Hat    Outerwear
161           170   27    Male           Belt    Outerwear
162           419   18    Male          Scarf     Clothing
163          2143   47    Male        Sweater  Accessories
164          2006   18    Male     Sunglasses     Footwear
165          3210   64  Female          Boots     Footwear
166          2007   58    Male          Pants  Accessories
167           597   23    Male       Backpack     Footwear
168          1631   63    Male          Shoes     Footwear
169           677   28    Male         Jacket     Clothing
170          1158   37    Male          Pants  Accessories
171           724   35    Male          Shirt  Accessories
172          2563   57    Male         Blouse     Clothing
173          3097   69  Female          Shoes     Clothing
174          2999   31  Female         Jacket     Clothing
175           420   53    Male         Shorts     Clothing
176          3179   66  Female          Boots     Footwear
177           579   69    Male         Gloves     Footwear
178          3593   61  Female     Sunglasses     Footwear
179          1763   36    Male          Scarf     Footwear
180           117   55    Male          Shirt     Footwear
181          3686   47  Female         Blouse     Clothing
182           861   26    Male           Coat     Footwear
183          1737   57    Male        Jewelry     Clothing
184          1719   54    Male        Jewelry     Clothing
185           641   53    Male          Jeans     Clothing
186          2689   53  Female          Socks  Accessories
187          2867   54  Female         Blouse     Clothing
188          3547   60  Female          Shoes  Accessories
189            80   38    Male       Sneakers    Outerwear
190          3732   54  Female           Coat  Accessories
191          1979   45    Male         Hoodie  Accessories
192          3359   56  Female          Socks     Clothing
193          1229   55    Male          Pants    Outerwear
194          3569   29  Female     Sunglasses     Footwear
195          3117   50  Female        Sweater    Outerwear
196          1688   67    Male          Dress     Clothing
197          3583   23  Female         Blouse     Clothing
198          2757   42  Female     Sunglasses  Accessories
199           383   28    Male          Skirt     Clothing
200          1150   21    Male          Socks  Accessories
201          1975   27    Male         Blouse  Accessories
202          3367   38  Female          Shoes  Accessories
203          3499   47  Female        T-shirt     Footwear
204          2001   26    Male          Skirt  Accessories
205           913   24    Male          Dress     Clothing
206          1445   32    Male           Coat     Clothing
207           988   62    Male          Dress  Accessories
208          2071   56    Male         Blouse  Accessories
209          2712   30  Female          Dress  Accessories
210          1690   32    Male         Jacket     Clothing
211           710   49    Male          Shirt    Outerwear
212          2859   34  Female          Pants     Clothing
213           313   38    Male        Handbag     Clothing
214          1501   63    Male     Sunglasses     Clothing
215           929   67    Male          Skirt     Clothing
216          1342   26    Male        Sandals     Clothing
217          3790   56  Female           Belt     Clothing
218          3474   63  Female          Socks     Clothing
219           779   29    Male           Belt     Clothing
220           386   67    Male        Sandals     Clothing
221          1506   46    Male          Shirt  Accessories
222          1087   53    Male          Skirt  Accessories
223          2188   37    Male          Shoes     Clothing
224          3502   53  Female            Hat     Footwear
225          3441   45  Female          Scarf  Accessories
226           484   23    Male          Dress     Clothing
227          2269   66    Male        T-shirt     Clothing
228          2264   44    Male        Sandals  Accessories
229          3463   44  Female        Jewelry     Clothing
230          3770   51  Female           Coat  Accessories
231          3712   69  Female         Gloves  Accessories
232           177   53    Male          Shoes  Accessories
233          1275   54    Male          Boots  Accessories
234          1013   28    Male          Shoes     Footwear
235          2655   23  Female        Sweater    Outerwear
236          3316   48  Female           Belt  Accessories
237            48   55    Male         Gloves  Accessories
238          2539   18    Male          Shirt  Accessories
239           767   57    Male          Jeans  Accessories
240          2153   38    Male         Jacket     Clothing
241          2237   23    Male          Skirt     Clothing
242          3721   21  Female          Shirt  Accessories
243          1430   24    Male          Scarf     Clothing
244          3228   28  Female        Sandals  Accessories
245          1805   30    Male          Skirt     Clothing
246           490   49    Male         Blouse     Clothing
247          3027   55  Female           Belt     Clothing
248          2255   24    Male       Sneakers  Accessories
249          2993   41  Female            Hat     Clothing
250          3573   23  Female        T-shirt     Clothing
251           892   20    Male          Pants     Clothing
252           515   64    Male        Jewelry     Clothing
253          3176   35  Female       Backpack     Clothing
254          3884   34  Female          Pants  Accessories
255          1854   29    Male       Backpack     Clothing
256           935   45    Male          Jeans     Clothing
257            84   36    Male        Sweater     Clothing
258          3152   52  Female          Shirt     Clothing
259          3436   68  Female         Hoodie     Clothing
260          2567   35    Male        Sandals  Accessories
261          2228   40    Male        Sandals  Accessories
262          1095   25    Male        Sweater  Accessories
263           795   69    Male          Boots  Accessories
264           127   43    Male        Handbag     Clothing
265           904   44    Male         Blouse    Outerwear
266          1991   32    Male          Boots  Accessories
267           886   41    Male          Pants     Clothing
268          2451   68    Male         Shorts     Clothing
269          1870   18    Male          Shirt     Clothing
270          3549   63  Female          Jeans     Clothing
271           493   50    Male       Backpack     Clothing
272          3165   40  Female           Belt     Clothing
273          1557   43    Male            Hat     Clothing
274           107   64    Male     Sunglasses    Outerwear
275           164   54    Male          Shirt     Clothing
276           473   20    Male        Jewelry     Clothing
277          1538   68    Male          Dress     Footwear
278          1976   53    Male        Jewelry    Outerwear
279          1203   48    Male         Blouse  Accessories
280          1582   69    Male          Dress  Accessories
281          1723   46    Male         Jacket     Clothing
282          2409   23    Male        Sandals     Footwear
283          3106   48  Female         Hoodie     Clothing
284           684   33    Male         Blouse     Footwear
285          1471   43    Male          Boots     Footwear
286          1008   58    Male         Jacket  Accessories
287           277   25    Male         Shorts     Clothing
288          3476   48  Female          Pants     Footwear
289           396   37    Male          Skirt     Footwear
290           565   67    Male          Dress     Clothing
291           504   55    Male           Coat     Footwear
292          3063   51  Female         Gloves  Accessories
293          1263   29    Male          Shirt     Footwear
294          2154   35    Male        Jewelry     Clothing
295          2802   64  Female       Backpack     Clothing
296          3869   18  Female          Skirt     Clothing
297          3613   47  Female           Belt     Footwear
298          3257   60  Female     Sunglasses  Accessories
299          3854   61  Female        Jewelry  Accessories
300          2054   19    Male        Sweater  Accessories
301          3360   43  Female        Sandals  Accessories
302          3738   19  Female        T-shirt  Accessories
303          3261   39  Female         Gloves  Accessories
304          3311   45  Female       Backpack    Outerwear
305          2766   64  Female       Backpack  Accessories
306          2474   57    Male          Scarf     Clothing
307          2472   30    Male          Boots     Footwear
308          1393   31    Male         Hoodie  Accessories
309          1919   35    Male        Jewelry     Clothing
310          1434   70    Male          Boots     Clothing
311          2365   62    Male           Coat  Accessories
312          3366   43  Female         Gloves     Clothing
313           331   46    Male           Coat     Clothing
314          2364   60    Male       Backpack     Clothing
315          3530   55  Female         Jacket     Clothing
316           895   44    Male     Sunglasses     Clothing
317          1450   18    Male          Pants     Clothing
318           330   70    Male     Sunglasses     Clothing
319           195   51    Male       Sneakers  Accessories
320          1893   39    Male       Backpack    Outerwear
321          1818   32    Male        T-shirt     Clothing
322          1993   33    Male         Jacket     Clothing
323          1006   43    Male          Shirt  Accessories
324          3001   57  Female         Jacket     Footwear
325          2485   60    Male          Dress     Clothing
326          2950   25  Female          Scarf  Accessories
327          2748   18  Female          Shoes     Clothing
328          1350   21    Male          Socks     Clothing
329          1368   60    Male          Pants  Accessories
330          1085   34    Male        T-shirt     Clothing
331          3215   53  Female        Sandals     Clothing
332          3609   24  Female     Sunglasses  Accessories
333          1649   36    Male           Belt     Clothing
334          2386   41    Male     Sunglasses  Accessories
335          2322   50    Male           Coat     Footwear
336          2690   29  Female         Jacket     Clothing

In [265]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,180,64,Male,Scarf,Footwear,31.0,Illinois,M,Violet,Fall,4.9,Yes,Yes,9.0,Bank Transfer,Fortnightly
1,831,41,Male,Boots,Clothing,76.0,Wyoming,M,Maroon,Fall,4.2,Yes,Yes,5.0,Credit Card,Annually
2,625,55,Male,Skirt,Clothing,87.0,South Carolina,NaN,Pink,Fall,3.4,Yes,Yes,21.0,PayPal,Annually
3,1781,67,Male,Socks,Accessories,81.0,North Dakota,S,Gray,Summer,4.2,No,No,49.0,Credit Card,Weekly
4,1059,29,Male,Blouse,Accessories,33.0,New Mexico,L,Violet,Summer,3.1,No,Yes,NaN,Bank Transfer,Every 3 Months
5,1424,51,Male,Sandals,Footwear,60.0,Michigan,NaN,Black,Fall,3.5,No,Yes,12.0,Venmo,Every 3 Months
6,3368,44,Female,Shirt,Clothing,48.0,Tennessee,M,Blue,Summer,NaN,No,No,6.0,Venmo,Fortnightly
7,264,27,Male,Belt,Clothing,46.0,Iowa,M,Purple,Summer,NaN,Yes,Yes,NaN,Venmo,Monthly
8,2210,42,Male,Handbag,Footwear,NaN,Utah,XL,Beige,Summer,4.5,No,No,44.0,Bank Transfer,Quarterly
9,1514,22,Male,Hoodie,Clothing,35.0,Texas,M,Red,Spring,4.1,No,Yes,27.0,Cash,Monthly

In [266]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
3945,2865,58,Female,Pants,Clothing,43.0,Illinois,S,Maroon,Fall,3.6,No,No,31.0,Venmo,Weekly
3946,2263,53,Male,Jeans,Accessories,22.0,Arizona,M,Green,Winter,3.1,No,No,NaN,PayPal,Monthly
3947,2099,49,Male,Backpack,Clothing,28.0,Louisiana,M,White,Summer,3.3,No,No,20.0,Venmo,Quarterly
3948,550,31,Male,Shirt,Accessories,29.0,Arizona,S,Olive,Fall,3.6,Yes,Yes,37.0,Venmo,Bi-Weekly
3949,3211,30,Female,Backpack,Clothing,67.0,Nevada,M,Magenta,Summer,2.9,No,No,43.0,Venmo,Bi-Weekly

In [267]:
len(df)

3950

In [268]:
df.shape

(3950, 16)

In [269]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3950.000000,3950.000000,3389.000000,3342.000000,3399.000000
mean,1948.884304,44.042532,59.673355,3.755925,25.272727
std,1125.015331,15.214836,23.621470,0.714216,14.501610
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,978.250000,31.000000,39.000000,3.100000,13.000000
50%,1944.500000,44.000000,59.000000,3.800000,25.000000
75%,2924.750000,57.000000,80.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [270]:
df.describe (include ="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,3950.000000,3950.000000,3950,3950,3950,3389.000000,3950,3573,3950,3950,3342.000000,3950,3950,3399.000000,3950,3950
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,2,NaN,6,7
top,NaN,NaN,Male,Jewelry,Clothing,NaN,California,M,Olive,Spring,NaN,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2688,174,1760,NaN,96,1606,180,1018,NaN,2884,2247,NaN,683,588
mean,1948.884304,44.042532,NaN,NaN,NaN,59.673355,NaN,NaN,NaN,NaN,3.755925,NaN,NaN,25.272727,NaN,NaN
std,1125.015331,15.214836,NaN,NaN,NaN,23.621470,NaN,NaN,NaN,NaN,0.714216,NaN,NaN,14.501610,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,1.000000,NaN,NaN
25%,978.250000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,13.000000,NaN,NaN
50%,1944.500000,44.000000,NaN,NaN,NaN,59.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,25.000000,NaN,NaN
75%,2924.750000,57.000000,NaN,NaN,NaN,80.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,50.000000,NaN,NaN

In [271]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3950 entries, 0 to 3949
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3950 non-null   int64
 1   Age                     3950 non-null   int64
 2   Gender                  3950 non-null   str
 3   Item Purchased          3950 non-null   str
 4   Category                3950 non-null   str
 5   Purchase Amount (USD)   3389 non-null   float64
 6   Location                3950 non-null   str
 7   Size                    3573 non-null   str
 8   Color                   3950 non-null   str
 9   Season                  3950 non-null   str
 10  Review Rating           3342 non-null   float64
 11  Subscription Status     3950 non-null   str
 12  Discount Applied        3950 non-null   str
 13  Previous Purchases      3399 non-null   float64
 14  Payment Method          3950 non-null   str
 15  Frequency of Purchases  3950 non-null   str
dtypes: float64(3), int64(2), str(11)
memory usage: 493.9 KB

In [272]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     561
Location                    0
Size                      377
Color                       0
Season                      0
Review Rating             608
Subscription Status         0
Discount Applied            0
Previous Purchases        551
Payment Method              0
Frequency of Purchases      0
dtype: int64

Data cleaning

In [273]:
df['Item Purchased'].unique()

<StringArray>
[     'Scarf',      'Boots',      'Skirt',      'Socks',     'Blouse',
    'Sandals',      'Shirt',       'Belt',    'Handbag',     'Hoodie',
      'Dress',        'Hat',       'Coat',      'Pants', 'Sunglasses',
      'Jeans',      'Shoes',     'Shorts',     'Jacket',    'Jewelry',
     'Gloves',    'Sweater',   'Sneakers',    'T-shirt',   'Backpack']
Length: 25, dtype: str

In [274]:
df['Category'].unique()

<StringArray>
['Footwear', 'Clothing', 'Accessories', 'Outerwear']
Length: 4, dtype: str

In [275]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories    [Socks, Blouse, Boots, Hat, Scarf, Belt, Coat, Handbag, Shoes, Shorts, Jewelry, Sweater, Sneakers, Pants, T-shirt, Hoodie, Jeans, Jacket, Backpack, Sunglasses, Dress, Skirt, Shirt, Sandals, Gloves]
Clothing       [Boots, Skirt, Shirt, Belt, Hoodie, Hat, Dress, Coat, Blouse, Pants, Sunglasses, Jeans, Scarf, Jacket, Shorts, Handbag, Gloves, Sneakers, Sweater, T-shirt, Jewelry, Sandals, Socks, Backpack, Shoes]
Footwear       [Scarf, Sandals, Handbag, Skirt, Socks, Sunglasses, Hat, Jewelry, Gloves, Pants, Coat, Belt, Sweater, Shirt, T-shirt, Boots, Backpack, Shoes, Dress, Blouse, Jacket, Jeans, Sneakers, Shorts, Hoodie]
Outerwear      [Dress, Shorts, Sneakers, Sandals, Boots, Blouse, Sweater, Jacket, Belt, Coat, Hoodie, T-shirt, Scarf, Hat, Pants, Shirt, Sunglasses, Jewelry, Backpack, Socks, Gloves, Jeans, Skirt, Handbag, Shoes]
Name: Item Purchased, dtype: object

In [276]:
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

Fix category and Item purchased column

In [277]:
correct_mapping = {
    #Clothing 
 "Skirt" : "Clothing", "Socks" : "Clothing", "Blouse" : "Clothing", "Shirt" : "Clothing", "Hoodie":"Clothing","Dress" : "Clothing", "Pants" : "Clothing","Jeans" : "Clothing","Shorts" : "Clothing", "Sweater" : "Clothing", "T-shirt" : "Clothing",
 #Accessories  
 "Scarf" : "Accessories" , "Belt" : "Accessories" , "Handbag" : "Accessories" , "Hat" : "Accessories" , "Sunglasses" : "Accessories" , "Jewelry" : "Accessories" , "Gloves" : "Accessories" , "T-Shirt" : "Accessories",
 #Footwear 
 "Boots" : "Footwear", "Sandals" : "Footwear","Shoes" : "Footwear", "Sneakers" : "Footwear",
 #Outwear
 "Coat" : "Outerwear", "Jacket" : "Outerwear"
}

In [278]:
correct_mapping

{'Skirt': 'Clothing',
 'Socks': 'Clothing',
 'Blouse': 'Clothing',
 'Shirt': 'Clothing',
 'Hoodie': 'Clothing',
 'Dress': 'Clothing',
 'Pants': 'Clothing',
 'Jeans': 'Clothing',
 'Shorts': 'Clothing',
 'Sweater': 'Clothing',
 'T-shirt': 'Clothing',
 'Scarf': 'Accessories',
 'Belt': 'Accessories',
 'Handbag': 'Accessories',
 'Hat': 'Accessories',
 'Sunglasses': 'Accessories',
 'Jewelry': 'Accessories',
 'Gloves': 'Accessories',
 'T-Shirt': 'Accessories',
 'Boots': 'Footwear',
 'Sandals': 'Footwear',
 'Shoes': 'Footwear',
 'Sneakers': 'Footwear',
 'Coat': 'Outerwear',
 'Jacket': 'Outerwear'}

In [279]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,180,64,Male,Scarf,Footwear,31.0,Illinois,M,Violet,Fall,4.9,Yes,Yes,9.0,Bank Transfer,Fortnightly
1,831,41,Male,Boots,Clothing,76.0,Wyoming,M,Maroon,Fall,4.2,Yes,Yes,5.0,Credit Card,Annually
2,625,55,Male,Skirt,Clothing,87.0,South Carolina,NaN,Pink,Fall,3.4,Yes,Yes,21.0,PayPal,Annually
3,1781,67,Male,Socks,Accessories,81.0,North Dakota,S,Gray,Summer,4.2,No,No,49.0,Credit Card,Weekly
4,1059,29,Male,Blouse,Accessories,33.0,New Mexico,L,Violet,Summer,3.1,No,Yes,NaN,Bank Transfer,Every 3 Months

In [280]:
df['Category'] = df['Item Purchased'].map(correct_mapping)

In [281]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories                                [Scarf, Belt, Handbag, Hat, Sunglasses, Jewelry, Gloves]
Clothing       [Skirt, Socks, Blouse, Shirt, Hoodie, Dress, Pants, Jeans, Shorts, Sweater, T-shirt]
Footwear                                                          [Boots, Sandals, Shoes, Sneakers]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

Treating the null values

In [282]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                  146
Purchase Amount (USD)     561
Location                    0
Size                      377
Color                       0
Season                      0
Review Rating             608
Subscription Status         0
Discount Applied            0
Previous Purchases        551
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [283]:
df['Size'].unique()

<StringArray>
['M', nan, 'S', 'L', 'XL']
Length: 5, dtype: str

In [284]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,180,64,Male,Scarf,Accessories,31.0,Illinois,M,Violet,Fall,4.9,Yes,Yes,9.0,Bank Transfer,Fortnightly
1,831,41,Male,Boots,Footwear,76.0,Wyoming,M,Maroon,Fall,4.2,Yes,Yes,5.0,Credit Card,Annually
2,625,55,Male,Skirt,Clothing,87.0,South Carolina,NaN,Pink,Fall,3.4,Yes,Yes,21.0,PayPal,Annually
3,1781,67,Male,Socks,Clothing,81.0,North Dakota,S,Gray,Summer,4.2,No,No,49.0,Credit Card,Weekly
4,1059,29,Male,Blouse,Clothing,33.0,New Mexico,L,Violet,Summer,3.1,No,Yes,NaN,Bank Transfer,Every 3 Months

In [285]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [M, XL, L, S, nan]
Clothing       [nan, S, L, M, XL]
Footwear       [M, nan, XL, L, S]
Outerwear      [S, XL, L, M, nan]
Name: Size, dtype: object

In [286]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories                                [Scarf, Belt, Handbag, Hat, Sunglasses, Jewelry, Gloves]
Clothing       [Skirt, Socks, Blouse, Shirt, Hoodie, Dress, Pants, Jeans, Shorts, Sweater, T-shirt]
Footwear                                                          [Boots, Sandals, Shoes, Sneakers]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

Treating null values or replacing all values in Accessories Category

In [287]:
df.loc[df['Category'] == 'Accessories', 'Size'] = "Free Size"

In [288]:
df.groupby('Category')['Size'].unique()

Category
Accessories           [Free Size]
Clothing       [nan, S, L, M, XL]
Footwear       [M, nan, XL, L, S]
Outerwear      [S, XL, L, M, nan]
Name: Size, dtype: object

In [289]:
df.loc[df['Category'] == 'Footwear', 'Size'] = "Not Available"

In [290]:
df.loc[(df['Category'] == 'Clothing') & (df["Size"].isnull()),"Size"]  = df[df ["Category"] == "Clothing"]["Size"].mode() [0]

In [291]:
df.groupby('Category')['Size'].unique()

Category
Accessories           [Free Size]
Clothing            [M, S, L, XL]
Footwear          [Not Available]
Outerwear      [S, XL, L, M, nan]
Name: Size, dtype: object

In [292]:
df.loc[(df['Category'] == 'Outerwear') & (df["Size"].isnull()),"Size"]  = df[df ["Category"] == "Outerwear"]["Size"].mode() [0]

In [293]:
df.groupby('Category')['Size'].unique()

Category
Accessories        [Free Size]
Clothing         [M, S, L, XL]
Footwear       [Not Available]
Outerwear        [S, XL, L, M]
Name: Size, dtype: object

Treating Category Column

In [294]:
df['Category'] = df['Category'].fillna(df['Category'].mode()[0])

Treating Size Column

In [295]:
df['Size'].isnull().sum()

np.int64(21)

In [296]:
df['Size'] = df.groupby('Category')['Size'].transform(
    lambda x: x.fillna(x.mode()[0]))

In [297]:
df['Size']

0           Free Size
1       Not Available
2                   M
3                   S
4                   L
5       Not Available
6                   M
7           Free Size
8           Free Size
9                   M
10                  M
11      Not Available
12                  M
13          Free Size
14                  M
15                  M
16          Free Size
17                  M
18                  S
19                  M
20          Free Size
21                  L
22                  L
23                  M
24                 XL
25          Free Size
26          Free Size
27                  M
28                  S
29          Free Size
30      Not Available
31                  M
32          Free Size
33                  M
34                  L
35          Free Size
36                 XL
37          Free Size
38          Free Size
39          Free Size
40          Free Size
41          Free Size
42          Free Size
43          Free Size
44                  M
45                  M
46          Free Size
47      Not Available
48                  M
49                  S
50      Not Available
51      Not Available
52      Not Available
53          Free Size
54      Not Available
55      Not Available
56      Not Available
57                  M
58      Not Available
59                  M
60                  S
61          Free Size
62          Free Size
63                  L
64                  S
65                  L
66                  M
67                  M
68                  M
69                 XL
70          Free Size
71                  L
72          Free Size
73                  M
74                 XL
75          Free Size
76          Free Size
77      Not Available
78                  M
79      Not Available
80                  M
81                  L
82                  M
83                  S
84          Free Size
85      Not Available
86          Free Size
87          Free Size
88                  L
89      Not Available
90                  M
91                  M
92          Free Size
93                  M
94                  M
95                  M
96          Free Size
97          Free Size
98      Not Available
99      Not Available
100         Free Size
101         Free Size
102                 L
103                 S
104                 S
105                 M
106                 L
107                 M
108                 M
109                 S
110         Free Size
111                 M
112                XL
113                 S
114         Free Size
115                 M
116                 S
117                 M
118     Not Available
119                 L
120                 S
121                 M
122                 L
123         Free Size
124                 M
125                 M
126         Free Size
127         Free Size
128                 S
129                XL
130                 M
131                 M
132         Free Size
133                 M
134                 L
135                 M
136                 L
137                 L
138                 L
139     Not Available
140                 M
141                 L
142                 L
143         Free Size
144                 M
145                 L
146                 L
147                XL
148     Not Available
149                 M
150     Not Available
151                 M
152         Free Size
153                 M
154                 M
155                 M
156                 M
157                 M
158         Free Size
159         Free Size
160         Free Size
161         Free Size
162         Free Size
163                 M
164         Free Size
165     Not Available
166                 S
167                 M
168     Not Available
169                 M
170                 M
171                 L
172                XL
173     Not Available
174                 M
175                 S
176     Not Available
177         Free Size
178         Free Size
179         Free Size
180                 S
181                 L
182                 M
183         Free Size
184         Free Size
185                 M
186                 M
187                 M
188     Not Available
189     Not Available
190                 M
191                 L
192                 M
193                 S
194         Free Size
195                 L
196                 S
197                 S
198         Free Size
199                 M
200                 L
201                 M
202     Not Available
203                 M
204                 M
205                 M
206                 L
207                 M
208                 M
209                 L
210                 L
211                 L
212                 L
213         Free Size
214         Free Size
215                XL
216     Not Available
217         Free Size
218                 M
219         Free Size
220     Not Available
221                 M
222                 M
223     Not Available
224         Free Size
225         Free Size
226                 M
227                 L
228     Not Available
229         Free Size
230                 L
231         Free Size
232     Not Available
233     Not Available
234     Not Available
235                 S
236         Free Size
237         Free Size
238                 M
239                 M
240                 M
241                 M
242                 M
243         Free Size
244     Not Available
245                 L
246                 M
247         Free Size
248     Not Available
249         Free Size
250                 M
251                 S
252         Free Size
253                 M
254                XL
255                XL
256                 S
257                 M
258                 L
259                 M
260     Not Available
261     Not Available
262                 M
263     Not Available
264         Free Size
265                 M
266     Not Available
267                 L
268                 M
269                 S
270                 M
271                 M
272         Free Size
273         Free Size
274         Free Size
275                 M
276         Free Size
277                 L
278         Free Size
279                 S
280                 L
281                 L
282     Not Available
283                 M
284                 S
285     Not Available
286                XL
287                XL
288                 M
289                 M
290                 M
291                 M
292         Free Size
293                 L
294         Free Size
295                 M
296                XL
297         Free Size
298         Free Size
299         Free Size
300                 S
301     Not Available
302                 S
303         Free Size
304                 M
305                 M
306         Free Size
307     Not Available
308                 M
309         Free Size
310     Not Available
311                 L
312         Free Size
313                 M
314                XL
315                 S
316         Free Size
317                 L
318         Free Size
319     Not Available
320                 M
321                 M
322                 L
323                 M
324                 M
325                 M
326         Free Size
327     Not Available
328                XL
329                 S
330                 S
331     Not Available
332         Free Size
333         Free Size
334         Free Size
335                 M
336                 M
337                 L
338                 S
339         Free Size
340                 M
341         Free Size
342                 M
343                 S
344         Free Size
345         Free Size
346                 S
347         Free Size
348                 L
349         Free Size
350         Free Size
351                XL
352                 S
353                 M
354                 M
355         Free Size
356                 S
357                 S
358                 L
359                 M
360         Free Size
361         Free Size
362                 M
363         Free Size
364         Free Size
365                 M
366                XL
367                 L
368         Free Size
369         Free Size
370                 M
371                 S
372                 S
373     Not Available
374     Not Available
375                 M
376                 M
377                 M
378         Free Size
379                 L
380         Free Size
381         Free Size
382         Free Size
383                 M
384                 L
385                 L
386     Not Available
387                 M
388                 S
389     Not Available
390     Not Available
391                 M
392     Not Available
393                 M
394                 M
395                 S
396                XL
397                 L
398                 L
399     Not Available
400                 M
401         Free Size
402                 M
403     Not Available
404         Free Size
405                XL
406         Free Size
407     Not Available
408     Not Available
409                 M
410                 M
411         Free Size
412         Free Size
413                 M
414         Free Size
415                 M
416         Free Size
417         Free Size
418                 S
419                 M
420                 L
421                XL
422         Free Size
423                 S
424         Free Size
425                 S
426                 L
427                 M
428         Free Size
429                 M
430     Not Available
431                 M
432                 M
433                 L
434                 L
435                 M
436         Free Size
437         Free Size
438                 S
439         Free Size
440         Free Size
441                 L
442                XL
443                 M
444     Not Available
445         Free Size
446                 S
447     Not Available
448         Free Size
449                 M
450                 M
451         Free Size
452     Not Available
453     Not Available
454         Free Size
455         Free Size
456                 L
457                 M
458         Free Size
459                 L
460         Free Size
461                 M
462                XL
463                 M
464                 L
465                 L
466                 M
467                 M
468                 M
469         Free Size
470         Free Size
471     Not Available
472                 L
473                 M
474                XL
475     Not Available
476                 M
477                 M
478         Free Size
479     Not Available
480     Not Available
481                XL
482                 M
483         Free Size
484         Free Size
485         Free Size
486     Not Available
487                 L
488         Free Size
489     Not Available
490         Free Size
491                 M
492         Free Size
493         Free Size
494                 M
495     Not Available
496                 M
497                 S
498                 M
499         Free Size
500                 M
501     Not Available
502                 M
503                XL
504                 M
505                 S
506                 S
507         Free Size
508                 L
509                 L
510                 S
511                 S
512                 L
513     Not Available
514                 M
515                 L
516                XL
517                XL
518                 L
519         Free Size
520         Free Size
521         Free Size
522         Free Size
523     Not Available
524                 M
525                 M
526         Free Size
527         Free Size
528     Not Available
529                 M
530                 M
531         Free Size
532                 M
533                 M
534                 S
535                 L
536                 L
537                 M
538     Not Available
539                 L
540     Not Available
541                 M
542                XL
543         Free Size
544     Not Available
545         Free Size
546                 S
547                 S
548     Not Available
549                 M
550         Free Size
551                 L
552     Not Available
553                 S
554                 M
555                 M
556         Free Size
557                 M
558     Not Available
559                 S
560                 S
561                 M
562         Free Size
563         Free Size
564         Free Size
565                XL
566                 M
567         Free Size
568                 L
569         Free Size
570         Free Size
571                 L
572     Not Available
573         Free Size
574                 M
575         Free Size
576                 M
577                 M
578     Not Available
579                 M
580                 S
581                XL
582         Free Size
583         Free Size
584                 M
585                XL
586                 L
587                 M
588         Free Size
589     Not Available
590                 M
591         Free Size
592                 L
593         Free Size
594                 M
595         Free Size
596                 M
597                 M
598         Free Size
599                 M
600     Not Available
601                 S
602                 S
603         Free Size
604                 L
605         Free Size
606                 L
607                 L
608                XL
609         Free Size
610                XL
611                 L
612     Not Available
613     Not Available
614                 M
615         Free Size
616         Free Size
617                XL
618                 M
619         Free Size
620         Free Size
621         Free Size
622                 L
623                 M
624                 S
625                 L
626         Free Size
627                 L
628     Not Available
629                 M
630                 M
631                 M
632         Free Size
633         Free Size
634                 S
635         Free Size
636                 M
637                XL
638         Free Size
639                 M
640                 S
641     Not Available
642                 M
643                 M
644                 L
645                XL
646                XL
647                 M
648         Free Size
649         Free Size
650                 M
651                 M
652                 M
653         Free Size
654     Not Available
655         Free Size
656                XL
657         Free Size
658                 M
659                 S
660         Free Size
661     Not Available
662     Not Available
663                 M
664         Free Size
665     Not Available
666                 M
667                 M
668                 M
669         Free Size
670                 L
671         Free Size
672                XL
673         Free Size
674         Free Size
675                 M
676                 S
677                 L
678     Not Available
679                 M
680                 M
681         Free Size
682         Free Size
683                 M
684                 M
685                 L
686         Free Size
687                 L
688         Free Size
689                 M
690                 L
691                 S
692         Free Size
693         Free Size
694     Not Available
695     Not Available
696         Free Size
697         Free Size
698     Not Available
699                XL
700         Free Size
701         Free Size
702         Free Size
703         Free Size
704                 L
705                 S
706                 L
707                 M
708                 M
709                 S
710     Not Available
711                 S
712         Free Size
713     Not Available
714         Free Size
715                 L
716                 M
717                 L
718                XL
719                 L
720         Free Size
721                 M
722         Free Size
723                 M
724                 S
725                 M
726         Free Size
727                 M
728                XL
729         Free Size
730                XL
731                 L
732                 S
733                 M
734         Free Size
735     Not Available
736         Free Size
737         Free Size
738                 M
739                 M
740         Free Size
741                 M
742                 L
743                 M
744                XL
745     Not Available
746                 S
747                 M
748                 M
749     Not Available
750         Free Size
751         Free Size
752         Free Size
753                XL
754     Not Available
755                XL
756         Free Size
757     Not Available
758                 M
759         Free Size
760                XL
761                 S
762                 M
763                 M
764                 L
765         Free Size
766     Not Available
767     Not Available
768                 M
769                 M
770     Not Available
771                 S
772                 M
773                 M
774                 S
775                 S
776         Free Size
777                 S
778         Free Size
779                 M
780     Not Available
781         Free Size
782                 M
783                 M
784     Not Available
785     Not Available
786     Not Available
787         Free Size
788         Free Size
789                XL
790                 L
791                 M
792     Not Available
793                 M
794                 L
795         Free Size
796         Free Size
797         Free Size
798                XL
799                 S
800         Free Size
801         Free Size
802                 M
803                XL
804     Not Available
805                 M
806                 M
807     Not Available
808                 L
809         Free Size
810                 M
811         Free Size
812                 S
813                 M
814     Not Available
815     Not Available
816     Not Available
817                 M
818     Not Available
819                 M
820     Not Available
821     Not Available
822         Free Size
823                 S
824                 M
825         Free Size
826                 M
827                 M
828         Free Size
829         Free Size
830                 S
831     Not Available
832         Free Size
833     Not Available
834                 L
835                 S
836                 M
837                 M
838         Free Size
839                 L
840                 S
841                 M
842     Not Available
843                 M
844                 M
845                 S
846                 M
847                 S
848                 M
849         Free Size
850                 L
851         Free Size
852                 S
853         Free Size
854     Not Available
855                 M
856                 L
857     Not Available
858         Free Size
859     Not Available
860         Free Size
861                 L
862         Free Size
863                 L
864         Free Size
865                 M
866         Free Size
867                 M
868     Not Available
869         Free Size
870                 M
871         Free Size
872     Not Available
873     Not Available
874                 S
875                 L
876                 M
877                 M
878     Not Available
879     Not Available
880         Free Size
881         Free Size
882                 L
883                 M
884                 L
885         Free Size
886     Not Available
887     Not Available
888         Free Size
889                 L
890         Free Size
891     Not Available
892     Not Available
893                 M
894                 L
895                 S
896                 L
897     Not Available
898                 M
899                 M
900                 M
901                 S
902         Free Size
903     Not Available
904     Not Available
905                 S
906         Free Size
907     Not Available
908     Not Available

In [298]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     561
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating             608
Subscription Status         0
Discount Applied            0
Previous Purchases        551
Payment Method              0
Frequency of Purchases      0
dtype: int64

Treating Review Rating Null Values

In [299]:
df['Review Rating'].mean()

np.float64(3.755924596050269)

In [300]:
df['Review Rating'].median()

np.float64(3.8)

In [301]:
df['Review Rating'].mode()

0    4.0
Name: Review Rating, dtype: float64

In [302]:
df.groupby("Item Purchased")['Review Rating'].mean()

Item Purchased
Backpack      3.719672
Belt          3.748529
Blouse        3.746575
Boots         3.714050
Coat          3.935766
Dress         3.847333
Gloves        3.623478
Handbag       3.656716
Hat           3.694203
Hoodie        3.677863
Jacket        3.783582
Jeans         3.768421
Jewelry       3.777333
Pants         3.824324
Sandals       3.617037
Scarf         3.741406
Shirt         3.786897
Shoes         3.736296
Shorts        3.679104
Skirt         3.671094
Sneakers      3.828455
Socks         3.833803
Sunglasses    3.788095
Sweater       3.802041
T-shirt       3.848780
Name: Review Rating, dtype: float64

In [303]:
df['Review Rating'] = df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'].transform('mean'))

In [304]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     561
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Discount Applied            0
Previous Purchases        551
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [305]:
df.head(16)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,180,64,Male,Scarf,Accessories,31.0,Illinois,Free Size,Violet,Fall,4.900000,Yes,Yes,9.0,Bank Transfer,Fortnightly
1,831,41,Male,Boots,Footwear,76.0,Wyoming,Not Available,Maroon,Fall,4.200000,Yes,Yes,5.0,Credit Card,Annually
2,625,55,Male,Skirt,Clothing,87.0,South Carolina,M,Pink,Fall,3.400000,Yes,Yes,21.0,PayPal,Annually
3,1781,67,Male,Socks,Clothing,81.0,North Dakota,S,Gray,Summer,4.200000,No,No,49.0,Credit Card,Weekly
4,1059,29,Male,Blouse,Clothing,33.0,New Mexico,L,Violet,Summer,3.100000,No,Yes,NaN,Bank Transfer,Every 3 Months
5,1424,51,Male,Sandals,Footwear,60.0,Michigan,Not Available,Black,Fall,3.500000,No,Yes,12.0,Venmo,Every 3 Months
6,3368,44,Female,Shirt,Clothing,48.0,Tennessee,M,Blue,Summer,3.786897,No,No,6.0,Venmo,Fortnightly
7,264,27,Male,Belt,Accessories,46.0,Iowa,Free Size,Purple,Summer,3.748529,Yes,Yes,NaN,Venmo,Monthly
8,2210,42,Male,Handbag,Accessories,NaN,Utah,Free Size,Beige,Summer,4.500000,No,No,44.0,Bank Transfer,Quarterly
9,1514,22,Male,Hoodie,Clothing,35.0,Texas,M,Red,Spring,4.100000,No,Yes,27.0,Cash,Monthly
10,2756,59,Female,Socks,Clothing,97.0,Nevada,M,Indigo,Winter,3.300000,No,No,18.0,Credit Card,Annually
11,3675,35,Female,Boots,Footwear,65.0,Washington,Not Available,Blue,Winter,3.714050,No,No,41.0,Venmo,Fortnightly
12,140,49,Male,Dress,Clothing,95.0,Florida,M,White,Fall,3.800000,Yes,Yes,30.0,Venmo,Annually
13,2646,23,Male,Hat,Accessories,81.0,Louisiana,Free Size,Olive,Spring,4.000000,No,No,24.0,Bank Transfer,Bi-Weekly
14,2944,29,Female,Skirt,Clothing,NaN,Virginia,M,Orange,Spring,3.671094,No,No,37.0,Credit Card,Monthly
15,564,61,Male,Skirt,Clothing,99.0,Idaho,M,Black,Fall,4.400000,Yes,Yes,16.0,Debit Card,Quarterly

In [306]:
df['Review Rating'] = df['Review Rating'] .round(2)

In [307]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,180,64,Male,Scarf,Accessories,31.0,Illinois,Free Size,Violet,Fall,4.90,Yes,Yes,9.0,Bank Transfer,Fortnightly
1,831,41,Male,Boots,Footwear,76.0,Wyoming,Not Available,Maroon,Fall,4.20,Yes,Yes,5.0,Credit Card,Annually
2,625,55,Male,Skirt,Clothing,87.0,South Carolina,M,Pink,Fall,3.40,Yes,Yes,21.0,PayPal,Annually
3,1781,67,Male,Socks,Clothing,81.0,North Dakota,S,Gray,Summer,4.20,No,No,49.0,Credit Card,Weekly
4,1059,29,Male,Blouse,Clothing,33.0,New Mexico,L,Violet,Summer,3.10,No,Yes,NaN,Bank Transfer,Every 3 Months
5,1424,51,Male,Sandals,Footwear,60.0,Michigan,Not Available,Black,Fall,3.50,No,Yes,12.0,Venmo,Every 3 Months
6,3368,44,Female,Shirt,Clothing,48.0,Tennessee,M,Blue,Summer,3.79,No,No,6.0,Venmo,Fortnightly
7,264,27,Male,Belt,Accessories,46.0,Iowa,Free Size,Purple,Summer,3.75,Yes,Yes,NaN,Venmo,Monthly
8,2210,42,Male,Handbag,Accessories,NaN,Utah,Free Size,Beige,Summer,4.50,No,No,44.0,Bank Transfer,Quarterly
9,1514,22,Male,Hoodie,Clothing,35.0,Texas,M,Red,Spring,4.10,No,Yes,27.0,Cash,Monthly

Treating Previous Purchases

In [308]:
df['Previous Purchases'] = df['Previous Purchases'].fillna(0)

In [309]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     561
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

Treating Purchase Amount(USD) Column

In [310]:
df.groupby("Item Purchased")["Purchase Amount (USD)"].mean()

Item Purchased
Backpack      60.373016
Belt          56.138462
Blouse        55.597403
Boots         60.674419
Coat          60.007353
Dress         60.192857
Gloves        55.818182
Handbag       56.500000
Hat           60.369231
Hoodie        59.746269
Jacket        59.296296
Jeans         62.579439
Jewelry       63.738562
Pants         62.476190
Sandals       60.522059
Scarf         61.090226
Shirt         61.393333
Shoes         60.395522
Shorts        57.766423
Skirt         59.634328
Sneakers      58.897638
Socks         59.948529
Sunglasses    57.134752
Sweater       59.540000
T-shirt       62.500000
Name: Purchase Amount (USD), dtype: float64

Filling Null Values of Purchase Amount (USD) with the mean of each Item Purchased

In [311]:
df['Purchase Amount (USD)'] = df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean'))

In [312]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

Checking Duplicates

In [313]:
df.duplicated().sum()

np.int64(50)

In [314]:
df[df.duplicated()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
870,2802,64,Female,Backpack,Clothing,56.000000,New Mexico,M,Indigo,Winter,2.60,No,No,30.0,PayPal,Annually
1011,1282,29,Male,Jeans,Clothing,81.000000,New Jersey,M,Olive,Spring,4.50,No,Yes,8.0,Venmo,Bi-Weekly
1025,3540,29,Female,Sweater,Clothing,56.000000,New York,S,Green,Spring,3.20,No,No,0.0,Credit Card,Bi-Weekly
1177,1288,24,Male,Backpack,Clothing,28.000000,Utah,M,Blue,Winter,3.40,No,Yes,20.0,PayPal,Monthly
1360,1036,61,Male,Handbag,Accessories,89.000000,Georgia,Free Size,Brown,Fall,3.66,Yes,Yes,32.0,Venmo,Annually
1518,1760,68,Male,Jewelry,Accessories,58.000000,Louisiana,Free Size,Green,Spring,4.00,No,No,0.0,PayPal,Weekly
1549,1080,18,Male,Shorts,Clothing,33.000000,Oklahoma,S,Blue,Summer,4.40,No,Yes,48.0,Bank Transfer,Monthly
1562,1953,57,Male,Backpack,Clothing,82.000000,Maryland,L,Yellow,Summer,4.60,No,No,50.0,Cash,Bi-Weekly
1590,1695,20,Male,Belt,Accessories,67.000000,Mississippi,Free Size,Turquoise,Summer,2.70,No,No,20.0,Debit Card,Fortnightly
1721,2090,37,Male,T-shirt,Clothing,57.000000,Maryland,L,Gold,Spring,3.60,No,No,41.0,Credit Card,Every 3 Months
2105,1545,30,Male,Jewelry,Accessories,24.000000,Arkansas,Free Size,Maroon,Spring,3.90,No,Yes,17.0,Debit Card,Bi-Weekly
2113,431,24,Male,Dress,Clothing,40.000000,Texas,M,Brown,Summer,3.50,Yes,Yes,40.0,Debit Card,Annually
2135,3870,26,Female,Skirt,Clothing,64.000000,Arizona,M,Cyan,Spring,3.67,No,No,28.0,Bank Transfer,Annually
2149,3196,68,Female,Pants,Clothing,58.000000,Missouri,S,Red,Spring,4.90,No,No,36.0,Credit Card,Quarterly
2177,1150,21,Male,Socks,Clothing,42.000000,Georgia,L,Cyan,Spring,3.30,No,Yes,40.0,Venmo,Annually
2211,3099,66,Female,Sandals,Footwear,64.000000,New Mexico,Not Available,Cyan,Summer,3.30,No,No,50.0,Bank Transfer,Quarterly
2236,963,29,Male,Sweater,Clothing,64.000000,Michigan,L,Green,Spring,4.40,Yes,Yes,26.0,Debit Card,Fortnightly
2479,219,28,Male,Gloves,Accessories,45.000000,California,Free Size,Magenta,Spring,3.62,Yes,Yes,8.0,Credit Card,Quarterly
2533,3287,45,Female,Sweater,Clothing,67.000000,Illinois,M,Pink,Winter,5.00,No,No,4.0,Venmo,Fortnightly
2668,670,43,Male,Shorts,Clothing,89.000000,Illinois,M,Gray,Spring,3.30,Yes,Yes,0.0,Venmo,Bi-Weekly
2669,3366,43,Female,Gloves,Accessories,58.000000,Tennessee,Free Size,Teal,Fall,3.62,No,No,45.0,Credit Card,Every 3 Months
2787,3179,66,Female,Boots,Footwear,34.000000,Washington,Not Available,Beige,Spring,2.70,No,No,28.0,Credit Card,Annually
2802,521,51,Male,Jeans,Clothing,62.579439,South Carolina,M,White,Spring,3.90,Yes,Yes,20.0,Debit Card,Quarterly
2894,3408,46,Female,Socks,Clothing,46.000000,Alabama,S,Purple,Spring,2.60,No,No,20.0,Cash,Quarterly
2898,3010,62,Female,Shoes,Footwear,60.395522,Louisiana,Not Available,Silver,Winter,4.60,No,No,8.0,Venmo,Fortnightly
2916,3368,44,Female,Shirt,Clothing,48.000000,Tennessee,M,Blue,Summer,3.79,No,No,6.0,Venmo,Fortnightly
2953,1570,20,Male,Shoes,Footwear,63.000000,Hawaii,Not Available,Orange,Summer,2.90,No,Yes,29.0,Debit Card,Weekly
2968,1022,55,Male,Hat,Accessories,51.000000,Massachusetts,Free Size,Lavender,Winter,4.90,Yes,Yes,39.0,PayPal,Weekly
3022,2625,19,Male,Pants,Clothing,59.000000,South Dakota,M,Indigo,Summer,3.30,No,No,19.0,Credit Card,Annually
3026,931,26,Male,Boots,Footwear,78.000000,Hawaii,Not Available,Green,Fall,3.71,Yes,Yes,20.0,Credit Card,Bi-Weekly
3046,1751,31,Male,Jeans,Clothing,62.579439,Missouri,M,White,Fall,3.10,No,No,38.0,Venmo,Every 3 Months
3111,2617,61,Male,Jeans,Clothing,55.000000,Georgia,XL,Purple,Spring,3.60,No,No,46.0,Cash,Annually
3149,1079,37,Male,Shorts,Clothing,59.000000,Arizona,M,Silver,Fall,4.40,No,Yes,49.0,Credit Card,Fortnightly
3232,2839,51,Female,Coat,Outerwear,50.000000,Maine,M,Blue,Fall,3.70,No,No,2.0,Bank Transfer,Weekly
3238,1111,28,Male,Belt,Accessories,61.000000,Texas,Free Size,Cyan,Fall,3.00,No,Yes,31.0,Cash,Bi-Weekly
3375,1814,40,Male,Hat,Accessories,62.000000,Illinois,Free Size,Olive,Spring,3.50,No,No,24.0,PayPal,Weekly
3424,1521,21,Male,Sweater,Clothing,66.000000,Iowa,M,Brown,Summer,4.40,No,Yes,39.0,Cash,Quarterly
3487,156,63,Male,Shoes,Footwear,77.000000,Maine,Not Available,Olive,Spring,4.30,Yes,Yes,21.0,Bank Transfer,Quarterly
3603,1615,30,Male,Handbag,Accessories,41.000000,Kansas,Free Size,Gray,Summer,3.40,No,Yes,22.0,Cash,Bi-Weekly
3617,3017,30,Female,Blouse,Clothing,26.000000,Indiana,L,Lavender,Summer,4.90,No,No,31.0,Bank Transfer,Quarterly
3626,1426,59,Male,Jacket,Outerwear,40.000000,Wyoming,S,White,Winter,3.70,No,Yes,39.0,Credit Card,Annually
3704,1218,50,Male,Sweater,Clothing,63.000000,Nebraska,XL,Cyan,Fall,2.60,No,Yes,12.0,Cash,Every 3 Months
3715,1022,55,Male,Hat,Accessories,51.000000,Massachusetts,Free Size,Lavender,Winter,4.90,Yes,Yes,39.0,PayPal,Weekly
3720,595,35,Male,Gloves,Accessories,83.000000,Oklahoma,Free Size,Brown,Winter,2.50,Yes,Yes,6.0,Debit Card,Monthly
3723,3503,31,Female,Sweater,Clothing,62.000000,Massachusetts,M,Green,Fall,4.70,No,No,26.0,Bank Transfer,Quarterly
3734,526,51,Male,Dress,Clothing,37.000000,Iowa,M,Cyan,Spring,3.20,Yes,Yes,41.0,Debit Card,Monthly
3888,1328,52,Male,Shorts,Clothing,40.000000,Florida,M,Turquoise,Winter,3.68,No,Yes,37.0,Cash,Weekly
3898,2064,61,Male,Blouse,Clothing,55.597403,Indiana,M,Cyan,Fall,2.90,No,No,32.0,Cash,Monthly
3899,1706,39,Male,Scarf,Accessories,61.090226,South Dakota,Free Size,Cyan,Summer,3.40,No,No,49.0,Venmo,Bi-Weekly
3939,279,57,Male,Jewelry,Accessories,95.000000,Hawaii,Free Size,Orange,Spring,3.70,Yes,Yes,23.0,Debit Card,Annually

Deleting Duplicate Records

In [315]:
df = df.drop_duplicates(subset=['Customer ID'], keep ='first')

In [316]:
df.duplicated().sum()

np.int64(0)

Renaming the Headers

In [317]:

df.columns = ['_'.join(col.split()) for col in df.columns]


df.columns = df.columns.str.lower()

In [318]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'discount_applied',
       'previous_purchases', 'payment_method', 'frequency_of_purchases'],
      dtype='str')

Renaming Purchase Amount(USD) to purchase_amount

In [323]:
df = df.rename(columns = {"purchase_amount_(usd)":"purchase_amount"})

In [324]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'discount_applied',
       'previous_purchases', 'payment_method', 'frequency_of_purchases'],
      dtype='str')